import type { Metadata } from "next";
import HeaderLayout from "@/app/headerlayout";
import { ConfigProvider } from "antd";
import { transparent, primary, black, white } from "@/app/color";
import TokenChecker from "@/app/utils/TokenChekcker";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const borderRadius = 16;

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<TokenChecker>
			<ConfigProvider
				theme={{
					token: {
						colorPrimary: primary,
						borderRadius,
						colorText: black,
					},
					components: {
						Layout: {
							headerBg: transparent,
							headerHeight: 70,
							headerPadding: 10,
							paddingContentHorizontal: 100,
							bodyBg: white,
						},
						Menu: {
							colorBgContainer: transparent,
							colorPrimary: black,
							colorText: black,
							activeBarHeight: 5,
							itemPaddingInline: 30,
						},
						Button: {
							borderRadiusLG: borderRadius,
						},
						Segmented: {
							itemColor: black,
							itemActiveBg: primary,
							itemHoverColor: white,
							itemSelectedColor: white,
							controlItemBgActive: primary,
							trackBg: white,
							controlItemBgHover: white,
							colorBgLayout: primary,
							colorBgBase: primary,
							colorBgContainer: primary,
							itemHoverBg: primary,
							itemSelectedBg: primary,
							borderRadius,
						},
						Card: {
							borderRadius,
							colorTextDescription: black,
						},
					},
				}}
			>
				<HeaderLayout>{children}</HeaderLayout>
			</ConfigProvider>
		</TokenChecker>
	);
}
