import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import HeaderLayout from "@/app/headerlayout";
import Provider from "./utils/Provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<AntdRegistry>
					<Provider>
						<HeaderLayout>
							{children}
						</HeaderLayout>
					</Provider>
				</AntdRegistry>
			</body>
		</html>
	);
}
